StringFunctionTables = [
    "Adj_PHS",                              # 1
    "Adj_RSA",                              # 2
    "Adj_FAD",                              # 3
    "Adj_GET",                              # 4
    "Adj_ZAD",                              # 5
    "Tbg_DefChan",
    "Adj_FAL",
    "Adj_GAD",
    "Adj_DSC",
    "Tbg_AirCal",
    "Tbg_ChanCorr",
    "Tbg_Spacing",
    "Tbg_WaterBeamHardCorrection",
    "Tbg_WaterScaling",
    "Qua_Slice_IEC",
    "Qua_Slice_ConstRef",
    "Qua_Contrast_IEC",
    "Qua_Contrast_ConstRef",
    "Qua_Noise_ConstRef",
    "Qua_Homogeneity_ConstRef",
    "Qua_MTF_IEC",
    "Qua_MTF_ConstRef",
    "Qua_TubeVoltage_ConstRef",
    "Qua_TubeVoltage_IEC",
    "Qua_TubePowerLevel_DHHS",
    "Qua_TubePowerLevel_IEC",
    "Qua_ScanDuration_DHHS",
    "Tbg_AirCal_BascalOnly",
    "Qua_Homogeneity_IEC",
    "Qua_Noise_IEC",
    "QuaSlice",
    "QuaHomogeneity",
    "QuaNoise",
    "QuaMTF",
    "QuaContrast",
    "Qua_SagCorLightmarker_IEC",
    "Qua_SagCorLightmarker_ConstRef",
    "Qua_Lightmarker_IEC",
    "Qua_TopoPos_IEC",
    "Qua_TablePos_IEC",
    "Qua_Lightmarker_ConstRef",
    "Qua_TopoPos_ConstRef",
    "Qua_TablePos_ConstRef",
    "Qua_LowContrast_IEC",
    "Qua_LowContrast_ConstRef",
    "Qua_CTDIDose_IEC",
    "Qua_TopoDose_IEC",
    "Qua_CTDIDose_ConstRef",
    "Qua_BeamQuality_DHHS",
    "Qua_IECCTDIHEADID_IEC",
    "Qua_IECCTDIHEADID_ConstRef",
    "Qua_CTDIHEADID_DHHS",
    "QuaIECCTDIBODYID",
    "Qua_IECCTDIBODYID_IEC",
    "Qua_IECCTDIBODYID_ConstRef",
    "Qua_CTDIBODYID_DHHS",
    "Qua_DoseProfile_IEC",
    "Adj_FAD_Check",
    "Tbg_AirCal_CusCalib_BascalOnly",
]
##############################################

if __name__ == '__main__':
    pass
